suppressMessages(library(ez))
suppressMessages(library(ggplot2))
suppressMessages(library(multcomp))
suppressMessages(library(nlme))
suppressMessages(library(pastecs))
suppressMessages(library(pgirmess))
suppressMessages(library(reshape))
suppressMessages(library(WRS))
suppressMessages(library(e1071))
suppressMessages(library(afex))
suppressMessages(library(emmeans))
suppressMessages(library(rcompanion))
suppressMessages(library(psych))
suppressMessages(library(tidyverse))

#myData <- read.csv(file="input/dataThreeCategories.csv", header=TRUE, sep=",")
#myData <- read.csv(file="output/meltedDataThreeCategories.csv", header=TRUE, sep=",")
myData <- read.csv(file="input/messageAcrossData.csv", header=TRUE, sep=",")
#myData$preferredVersion <- unclass(myData$preferredVersion)

personalityVariables <- c("Internal", "PowerfulOthers", "Chance")

invisible(lapply(personalityVariables, function(x) {
	print(x)
    corr <- cor.test(x=eval(substitute(myData$personality, list(personality = as.name(x)))), y=myData$meanWhatFocus, method = 'spearman', exact=FALSE)
    print(corr)
  }))

print(quantile(myData$Internal, c(.25, .75)))
print(quantile(myData$PowerfulOthers, c(.25, .75)))
print(quantile(myData$Chance, c(.25, .75)))