#!/bin/bash

echo "Removing old data..."
find . -name "*.messageAcrossData" -exec rm -f {} \;
rm -f "output/meltedData.csv"
find . -name "*.png" -exec rm -f {} \;


echo "Preparing data..."
python3 -W ignore ./scripts/melter.py

echo "Creating plots..."
Rscript ./scripts/plotsGenerator.r

echo "Analysing data..."
Rscript ./scripts/analiser.r

echo "Done"